-- Create a table for remote logging from the Android app
CREATE TABLE IF NOT EXISTS public.remote_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    tag TEXT,
    level TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.remote_logs ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert logs
CREATE POLICY "Allow Insert for Anyone" ON public.remote_logs
FOR INSERT
TO anon
WITH CHECK (true);

-- Allow anyone to read logs (for us to debug)
CREATE POLICY "Allow Select for Anyone" ON public.remote_logs
FOR SELECT
TO anon
USING (true);

-- Enable Realtime for logs (optional but helpful)
ALTER PUBLICATION supabase_realtime ADD TABLE public.remote_logs;
